### ISSUE TITLE
Fail to run demos while using QEMU 4.2.1

### ISSUE THREAD

**Issue by OscarShiang** [DavidSpickett/ARMMultiTasking#10] opened 2020-11-24 14:21 UTC
**Describe the bug**
The shell demo freezes at the beginning and fails to run. Other demos finish without any output. 

**Configuration:**
 - cmake version (`cmake --version`)
```
cmake version 3.16.3
```
 - toolchain/compiler version (`gcc --version`, for example)
```
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 9-2020-q2-update) 9.3.1 20200408 (release)

aarch64-none-elf-gcc (GNU Toolchain for the A-profile Architecture 9.2-2019.12 (arm-9.10)) 9.2.1 20191025
```
 - QEMU version (`qemu-system-arm --version`)
```
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.8)
```

**To Reproduce:**
- cmake configuration
```
-- BUILD_PLATFORM is arm
-- OPT_LEVEL is -O0
-- SANITIZERS are ON
-- LTO is OFF
-- COVERAGE is 
-- STACK_SIZE is 2KB
-- ccache is enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/oscar/ARMMultiTasking
```
- make command
```
make
```
- run command
```
make run_shell
```

**Expected behavior**
The demos will print out some log messages or let us to type something. 

**Affected platforms/settings**
It occurs on all platforms:
- arm
- thumb
- aarch64

**Additional context**
I think that it is a problem when using QEMU 4.2.1, since it successfully runs on QEMU 5.1.0. 

I use `git checkout` to some previous commit. It seems that the problem occurs after `b089ef2`. 

I try to use gdb to locate the error, but it turns out the shell demo works properly when I execute the code one by one. 
So I am not sure where the error is.

**Comment by DavidSpickett** [comment] 2020-11-24 17:26
Yeah this is https://github.com/DavidSpickett/ARMMultiTasking/commit/b089ef2c6e926e4e50afd5143b13776581deb3c4 for sure. I've seen something like it on another architecture.

There is some logic in qemu/target/arm/arm-semi.c that means the guest cannot close QEMU's stdout if it tries to close the stdout that QEMU gave to it. However this came in pretty recently: https://git.qemu.org/?p=qemu.git;a=commit;h=16ab12a936ef96b25be7f5981c96548fa772f3df

When we check for a TTY we:
* see if we can open stdout at all (this is a semihosting extension)
* if so open it, ask if it's a TTY
* then close it and carry on (this is where the issue happens)

If the linked patch is not present then we'll actually close QEMU's stdout (not just our stdout) so it can't print anything either. I think when you run the demo under debug there's some different path that keeps stdout open, I'm not too sure. Anyway that's not important.

QEMU 2.1 - Didn't implement the stdout semihosting extension at all (works)
QEMU 4.2.1 - Has the extension, with this issue (doesn't work)
QEMU 5.1.0 - Has the extension and the issue is fixed (works)

I *think* you can work around it by not closing stdout at the end of the sequence above, I haven't tested it myself. I think the serial port would still be able to print if we have stdout open.

**Comment by OscarShiang** [comment] 2020-11-25 02:51
> I think you can work around it by not closing stdout at the end of the sequence above, I haven't tested it myself. I think the serial port would still be able to print if we have stdout open.

I have tested this on QEMU 4.2.1 and QEMU 5.1.0. It works fine and prints out the coloured text successfully.

**Comment by OscarShiang** [comment] 2020-11-25 02:54
Do we just need to remove the `k_close` function or we need another way to fix it?

**Comment by DavidSpickett** [comment] 2020-11-25 18:14
Yeah remove https://github.com/DavidSpickett/ARMMultiTasking/blob/master/src/kernel/file.c#L53 and replace it with a comment stating what we're working around.

**Comment by OscarShiang** [comment] 2020-11-26 03:30
OK, I have created a PR to remove it.

**Closed as completed** 2020-11-26 18:07 UTC
Labels: bug
